export enum BookGenre {
  // Fiction
  'Literary Fiction' = 'Literary Fiction',
  'Science Fiction (Sci-Fi)' = 'Science Fiction (Sci-Fi)',
  'Fantasy' = 'Fantasy',
  'Mystery' = 'Mystery',
  'Thriller' = 'Thriller',
  'Horror' = 'Horror',
  'Romance' = 'Romance',
  'Historical Fiction' = 'Historical Fiction',
  // Non-Fiction
  'Biography/Autobiography' = 'Biography/Autobiography',
  'Memoir' = 'Memoir',
  'Self-Help' = 'Self-Help',
  'Business/Finance' = 'Business/Finance',
  'Psychology' = 'Psychology',
  'Health/Fitness' = 'Health/Fitness',
  'Travel' = 'Travel',
  'Cooking/Food' = 'Cooking/Food',
  'History' = 'History',
  'Politics' = 'Politics',
  'Science/Nature' = 'Science/Nature',
  'Technology/Computers' = 'Technology/Computers',
  // Children's
  'Picture Books' = 'Picture Books',
  'Early Readers' = 'Early Readers',
  'Chapter Books' = 'Chapter Books',
  'Middle Grade' = 'Middle Grade',
  'Young Adult (YA)' = 'Young Adult (YA)',
  // Poetry
  'Anthology' = 'Anthology',
  'Contemporary Poetry' = 'Contemporary Poetry',
  'Classic Poetry' = 'Classic Poetry',
  // Drama/Play
  'Tragedy' = 'Tragedy',
  'Comedy' = 'Comedy',
  'Historical Drama' = 'Historical Drama',
  'Modern Drama' = 'Modern Drama',
  // Graphic Novels/Comics
  'Superheroes' = 'Superheroes',
  'Manga' = 'Manga',
  'Graphic Memoirs' = 'Graphic Memoirs',
  // Religion/Spirituality
  'Christianity' = 'Christianity',
  'Islam' = 'Islam',
  'Buddhism' = 'Buddhism',
  'Hinduism' = 'Hinduism',
  'Judaism' = 'Judaism',
  'New Age/Spirituality' = 'New Age/Spirituality',
  // Reference
  'Dictionaries' = 'Dictionaries',
  'Encyclopedias' = 'Encyclopedias',
  'Almanacs' = 'Almanacs',
  'Atlases' = 'Atlases',
  'Thesauruses' = 'Thesauruses',
  // Art/Photography
  'Painting/Drawing' = 'Painting/Drawing',
  'Photography' = 'Photography',
  'Sculpture' = 'Sculpture',
  'Design' = 'Design',
  // Education/Textbooks
  'Academic Textbooks' = 'Academic Textbooks',
  'Educational Materials' = 'Educational Materials',
  'Teaching Resources' = 'Teaching Resources',
  // Crafts/Hobbies
  'DIY/Crafts' = 'DIY/Crafts',
  'Gardening' = 'Gardening',
  'Woodworking' = 'Woodworking',
  'Cooking/Baking' = 'Cooking/Baking',
  // Magazines/Journals
  'Fashion' = 'Fashion',
  'Lifestyle' = 'Lifestyle',
  'Science' = 'Science',
  'Technology' = 'Technology',
}
